rsooio - work1
west2-online-reserve/collection-frontends pull request #9
Opened 2023-10-03 17:06 UTC by rsooio

1. 基本实现响应式布局
2. 直接引用项目根目录下的图片，文件位置改动图片可能加载失败

2023-10-05 06:26 UTC, ROBINRUGAN commented
pr名字改一下，前面应该是学号

2023-10-05 08:18 UTC, ROBINRUGAN requested changes
### 问题如下：
- 背景颜色有点怪，选颜色的话可以使用取色器，这样就能所见即所得了。
- 然后就是，电脑显示的话，日期那一列的背景会丢失？然后移动端布局的话，表格背景直接无了。
- 导航栏可以可以再做细致一点，可以加一下背景、圆角和hover，然后如果觉得下划线比较丑的话可以把text-decoration去了
### 很棒啊，你是我见到的第一个把移动端布局给写了的，非常nice！把上面问题改改就很完美了。

2023-10-05 16:40 UTC, ROBINRUGAN commented
代码改完之后直接继续commit和push即可

2023-10-07 07:49 UTC, rsooio commented
发现 Chrome 和火狐对CSS处理有很大不同，正在修复 Chrome 样式

2023-10-07 08:13 UTC, rsooio commented
Chrome 样式已修复，媒体查询从 min-width 改成 min-device-width 修复

2023-10-07 15:04 UTC, ROBINRUGAN approved these changes

2023-10-07 15:07 UTC, ROBINRUGAN commented
可以的，写的很棒，还额外写了一套移动端的css，整个页面丝滑精美，作业要求也完成的很到位，是一份优秀作业。恭喜你完成前端第0轮和第1轮考核✨🎈

2023-10-07 15:07 UTC, merged